# NumPy Practice

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

In [45]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [46]:
# Create a 1-dimensional NumPy array using np.array()
array1d = np.array([1, 2, 3, 4, 5])


# Create a 2-dimensional NumPy array using np.array()
array2d = np.array([[1, 2, 3], [4, 5, 6]])


# Create a 3-dimensional Numpy array using np.array()
array3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [47]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("1D Array:")
print("Shape:", array1d.shape)
print("Dimensions:", array1d.ndim)
print("Data type:", array1d.dtype)
print("Size:", array1d.size)
print("Type:", type(array1d))

1D Array:
Shape: (5,)
Dimensions: 1
Data type: int64
Size: 5
Type: <class 'numpy.ndarray'>


In [48]:
# Attributes of 2-dimensional array
print("\n2D Array:")
print("Shape:", array2d.shape)
print("Dimensions:", array2d.ndim)
print("Data type:", array2d.dtype)
print("Size:", array2d.size)
print("Type:", type(array2d))


2D Array:
Shape: (2, 3)
Dimensions: 2
Data type: int64
Size: 6
Type: <class 'numpy.ndarray'>


In [49]:
# Attributes of 3-dimensional array
print("\n3D Array:")
print("Shape:", array3d.shape)
print("Dimensions:", array3d.ndim)
print("Data type:", array3d.dtype)
print("Size:", array3d.size)
print("Type:", type(array3d))


3D Array:
Shape: (2, 2, 2)
Dimensions: 3
Data type: int64
Size: 8
Type: <class 'numpy.ndarray'>


In [50]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

df = pd.DataFrame(array2d)
print(df)

   0  1  2
0  1  2  3
1  4  5  6


In [51]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10, 2))

In [52]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7, 2, 3))

In [53]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)

In [54]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7, 2))

In [55]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.rand(3, 5)

In [56]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
random_seeded_array = np.random.randint(0, 10, size=(4, 6))
print(random_seeded_array)



[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

# when you run the cell again, the numbers in the array will be the same. This happens because setting the random seed (np.random.seed(42)) ensures that the random number generator produces the same sequence of numbers every time.

In [57]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_3x7 = np.random.randint(1, 10, size=(3, 7))


# Find the unique numbers in the array you just created
unique_numbers = np.unique(random_array_3x7)
print(unique_numbers)

[1 2 3 4 5 7 9]


In [58]:
# Find the 0'th index of the latest array you created
print(random_array_3x7[0])

[9 1 3 7 4 9 3]


In [59]:
# Get the first 2 rows of latest array you created
print(random_array_3x7[:2])

[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]]


In [60]:
# Get the first 2 values of the first 2 rows of the latest array

print(random_array_3x7[:2, :2])


[[9 1]
 [5 3]]


In [61]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

random_array_3x5 = np.random.randint(0, 10, size=(3, 5))
ones_array_3x5 = np.ones((3, 5))



In [62]:
# Add the two arrays together
added_array = random_array_3x5 + ones_array_3x5
print(added_array)


[[ 7.  8.  3.  1.  4.]
 [ 2.  8.  4.  2.  6.]
 [ 6. 10.  4.  6.  2.]]


In [63]:
# Create another array of ones of shape (5, 3)
ones_array_5x3 = np.ones((5, 3))


In [64]:
# Try add the array of ones and the other most recent array together
added_arrays = random_array_3x5 + ones_array_5x3
print(added_arrays)

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

# # we need to reshape or transpose one of the arrays


In [65]:

# transpose the ones array to make it (3, 5)
transposed_ones = ones_array_5x3.T

added_array_fixed = random_array_3x5 + transposed_ones
print(added_array_fixed)

[[ 7.  8.  3.  1.  4.]
 [ 2.  8.  4.  2.  6.]
 [ 6. 10.  4.  6.  2.]]


In [66]:
# Create another array of ones of shape (3, 5)
new_ones_array = np.ones((3, 5))


In [67]:
# Subtract the new array of ones from the other most recent array
subtracted_array = random_array_3x5 - new_ones_array
print(subtracted_array)

[[ 5.  6.  1. -1.  2.]
 [ 0.  6.  2.  0.  4.]
 [ 4.  8.  2.  4.  0.]]


In [68]:
# Multiply the ones array with the latest array
multiplied_array = random_array_3x5 * new_ones_array
print(multiplied_array)

[[6. 7. 2. 0. 3.]
 [1. 7. 3. 1. 5.]
 [5. 9. 3. 5. 1.]]


In [69]:
# Take the latest array to the power of 2 using '**'
power_array = random_array_3x5 ** 2
print(power_array)

[[36 49  4  0  9]
 [ 1 49  9  1 25]
 [25 81  9 25  1]]


In [70]:
# Do the same thing with np.square()
square_array = np.square(random_array_3x5)
print(square_array)

[[36 49  4  0  9]
 [ 1 49  9  1 25]
 [25 81  9 25  1]]


In [71]:
# Find the mean of the latest array using np.mean()
mean_value = np.mean(random_array_3x5)
print("Mean:", mean_value)

Mean: 3.8666666666666667


In [72]:
# Find the maximum of the latest array using np.max()
max_value = np.max(random_array_3x5)
print("Max:", max_value)

Max: 9


In [73]:
# Find the minimum of the latest array using np.min()
min_value = np.min(random_array_3x5)
print("Min:", min_value)


Min: 0


In [74]:
# Find the standard deviation of the latest array
std_dev = np.std(random_array_3x5)
print("Standard Deviation:", std_dev)

Standard Deviation: 2.578543947441829


In [75]:
# Find the variance of the latest array
variance = np.var(random_array_3x5)
print("Variance:", variance)

Variance: 6.648888888888889


In [76]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = random_array_3x5.reshape((3, 5, 1))
print(reshaped_array)

[[[6]
  [7]
  [2]
  [0]
  [3]]

 [[1]
  [7]
  [3]
  [1]
  [5]]

 [[5]
  [9]
  [3]
  [5]
  [1]]]


In [77]:
# Transpose the latest array
transposed_array = random_array_3x5.T
print(transposed_array)

[[6 1 5]
 [7 7 9]
 [2 3 3]
 [0 1 5]
 [3 5 1]]


What does the transpose do?

# transpose flips the axes of the array

In [78]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original array:")
print(arr)  # Shape: (2, 3)

transposed_arr = arr.T
print("Transposed array:")
print(transposed_arr)  # Shape: (3, 2)

# transpose flips the axes of the array

Original array:
[[1 2 3]
 [4 5 6]]
Transposed array:
[[1 4]
 [2 5]
 [3 6]]


In [79]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1 = np.random.randint(0, 10, size=(3, 3))
array2 = np.random.randint(0, 10, size=(3, 2))


In [80]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(array1, array2)
print(dot_product)


[[ 88 117]
 [100 123]
 [ 89 127]]


In [81]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array3 = np.random.randint(0, 10, size=(4, 3))
array4 = np.random.randint(0, 10, size=(4, 3))


In [82]:
# Perform a dot product on the two newest arrays you created
dot_product2 = np.dot(array3, array4)
print(dot_product2)



ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [83]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
transposed_array4 = array4.T
dot_product_fixed = np.dot(array3, transposed_array4)
print(dot_product_fixed)

[[ 24 102  96   8]
 [ 16 114 106  63]
 [ 22 123 114  56]
 [  8  60  58   7]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [84]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array5 = np.random.randint(0, 10, size=(3, 3))
array6 = np.random.randint(0, 10, size=(3, 3))

In [85]:
# Compare the two arrays with '>'
comparison = array5 > array6
print(comparison)

[[ True  True  True]
 [ True False False]
 [False False False]]


What happens when you compare the arrays with `>`?

In [86]:
# Compare the two arrays with '>='
comparison_ge = array5 >= array6
print(comparison_ge)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [87]:
# Find which elements of the first array are greater than 7
greater_than_7 = array5 > 7
print(greater_than_7)

[[False False False]
 [False False False]
 [False False False]]


In [88]:
# Which parts of each array are equal? (try using '==')
equal_elements = array5 == array6
print(equal_elements)

[[False False False]
 [False False False]
 [False False False]]


In [89]:
# Sort one of the arrays you just created in ascending order
sorted_array = np.sort(array5)
print(sorted_array)

[[6 6 7]
 [2 4 7]
 [0 2 5]]


In [90]:
# Sort the indexes of one of the arrays you just created
sorted_indexes = np.argsort(array5)
print(sorted_indexes)

[[0 1 2]
 [1 0 2]
 [2 1 0]]


In [91]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(array5)
print(max_index)

2


In [92]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(array5)
print(min_index)

8


In [93]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indexes_axis1 = np.argmax(array5, axis=1)
print(max_indexes_axis1)

[2 2 0]


In [94]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indexes_axis0 = np.argmin(array5, axis=0)
print(min_indexes_axis0)

[1 1 2]


In [95]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)
print(evenly_spaced_array)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
